import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "./providers/queryClientProvider";
const encondeSans = Encode_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jogoteca",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${encondeSans.className} antialiased bg-blue-gray`}>
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  );
}
